-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package GpioRegisters_pkg is

    constant GPIOREGISTERS_DATA_WIDTH : positive := 32;
    constant GPIOREGISTERS_MIN_ADDR_WIDTH : positive := 4;
    constant GPIOREGISTERS_SIZE : positive := 12;

    type \GpioRegisters.input.input_in_t\ is record
        next_q : std_logic_vector(31 downto 0);
    end record;

    type \GpioRegisters.input_in_t\ is record
        input : \GpioRegisters.input.input_in_t\;
    end record;

    type GpioRegisters_in_t is record
        input : \GpioRegisters.input_in_t\;
    end record;

    type \GpioRegisters.direction.direction_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \GpioRegisters.direction_out_t\ is record
        direction : \GpioRegisters.direction.direction_out_t\;
    end record;

    type \GpioRegisters.output.output_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \GpioRegisters.output_out_t\ is record
        output : \GpioRegisters.output.output_out_t\;
    end record;

    type GpioRegisters_out_t is record
        direction : \GpioRegisters.direction_out_t\;
        output : \GpioRegisters.output_out_t\;
    end record;
end package;
