LIBRARY ieee;
CONTEXT ieee.ieee_std_context;

-- Convenience types and utility functions used by the autogenerated regblock code
PACKAGE reg_utils IS

    TYPE std_logic_array1 IS ARRAY(NATURAL RANGE <>) OF STD_LOGIC;
    TYPE std_logic_array2 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC;
    TYPE std_logic_array3 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC;
    TYPE std_logic_array4 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC;
    TYPE std_logic_array5 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC;

    TYPE std_logic_vector_array1 IS ARRAY(NATURAL RANGE <>) OF STD_LOGIC_VECTOR;
    TYPE std_logic_vector_array2 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC_VECTOR;
    TYPE std_logic_vector_array3 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC_VECTOR;
    TYPE std_logic_vector_array4 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC_VECTOR;
    TYPE std_logic_vector_array5 IS ARRAY(NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>, NATURAL RANGE <>) OF STD_LOGIC_VECTOR;

    -- reverse bits of the input vector
    FUNCTION bitswap(vec : IN STD_LOGIC_VECTOR) RETURN STD_LOGIC_VECTOR;
    FUNCTION bitswap(logic : IN STD_LOGIC) RETURN STD_LOGIC;

    -- Autogenerating VHDL when dealing with programmatically defined field widths
    -- can be challenging, especially when doing arithmetic. These conversion functions
    -- are overloaded with various input types, allow them to work regardless
    -- of the input type or width.
    FUNCTION to_unsigned(vec : IN STD_LOGIC_VECTOR) RETURN unsigned;
    FUNCTION to_unsigned(logic : IN STD_LOGIC) RETURN unsigned;

    FUNCTION to_std_logic_vector(uns : IN unsigned) RETURN STD_LOGIC_VECTOR;
    FUNCTION to_std_logic_vector(logic : IN STD_LOGIC) RETURN STD_LOGIC_VECTOR;

    FUNCTION to_std_logic(bool : IN BOOLEAN) RETURN STD_LOGIC;
    FUNCTION to_std_logic(vec : IN STD_LOGIC_VECTOR(0 DOWNTO 0)) RETURN STD_LOGIC;
    FUNCTION to_std_logic(uns : IN unsigned(0 DOWNTO 0)) RETURN STD_LOGIC;

    -- reduction OR for tools with poor VHDL 2008 support
    FUNCTION or_reduce(vec : IN STD_LOGIC_VECTOR) RETURN STD_LOGIC;
    FUNCTION or_reduce(logic : IN STD_LOGIC) RETURN STD_LOGIC;

END PACKAGE reg_utils;

PACKAGE BODY reg_utils IS

    FUNCTION bitswap(vec : IN STD_LOGIC_VECTOR) RETURN STD_LOGIC_VECTOR IS
        VARIABLE result : STD_LOGIC_VECTOR(vec'RANGE);
        ALIAS swapped : STD_LOGIC_VECTOR(vec'REVERSE_RANGE) IS vec;
    BEGIN
        FOR i IN swapped'RANGE LOOP
            result(i) := swapped(i);
        END LOOP;
        RETURN result;
    END FUNCTION;

    FUNCTION bitswap(logic : IN STD_LOGIC) RETURN STD_LOGIC IS
    BEGIN
        RETURN logic;
    END FUNCTION;

    FUNCTION to_unsigned(vec : IN STD_LOGIC_VECTOR) RETURN unsigned IS
    BEGIN
        RETURN unsigned(vec);
    END FUNCTION;

    FUNCTION to_unsigned(logic : IN STD_LOGIC) RETURN unsigned IS
        VARIABLE result : unsigned(0 DOWNTO 0);
    BEGIN
        result(0) := logic;
        RETURN result;
    END FUNCTION;

    FUNCTION to_std_logic_vector(uns : IN unsigned) RETURN STD_LOGIC_VECTOR IS
    BEGIN
        RETURN STD_LOGIC_VECTOR(uns);
    END FUNCTION;

    FUNCTION to_std_logic_vector(logic : IN STD_LOGIC) RETURN STD_LOGIC_VECTOR IS
        VARIABLE result : STD_LOGIC_VECTOR(0 DOWNTO 0);
    BEGIN
        result(0) := logic;
        RETURN result;
    END FUNCTION;

    FUNCTION to_std_logic(bool : IN BOOLEAN) RETURN STD_LOGIC IS
    BEGIN
        IF bool = TRUE THEN
            RETURN '1';
        ELSE
            RETURN '0';
        END IF;
    END FUNCTION;

    FUNCTION to_std_logic(vec : IN STD_LOGIC_VECTOR(0 DOWNTO 0)) RETURN STD_LOGIC IS
    BEGIN
        RETURN vec(0);
    END FUNCTION;

    FUNCTION to_std_logic(uns : IN unsigned(0 DOWNTO 0)) RETURN STD_LOGIC IS
    BEGIN
        RETURN uns(0);
    END FUNCTION;

    FUNCTION or_reduce(vec : IN STD_LOGIC_VECTOR) RETURN STD_LOGIC IS
        VARIABLE result : STD_LOGIC;
    BEGIN
        result := '0';
        FOR i IN vec'RANGE LOOP
            result := result OR vec(i);
        END LOOP;
        RETURN result;
    END FUNCTION;

    FUNCTION or_reduce(logic : IN STD_LOGIC) RETURN STD_LOGIC IS
    BEGIN
        RETURN logic;
    END FUNCTION;

END PACKAGE BODY;