_default:
    @just --list

clean:
    rm -r build

# Assemble a file for the processor
assemble file:
    mkdir -p build
    riscv64-unknown-elf-as -march=rv32i -o build/program.o {{file}}
    riscv64-unknown-elf-ld -m elf32lriscv -T linker.ld -o build/program.elf build/program.o
    riscv64-unknown-elf-objcopy -O binary build/program.elf build/program.bin
    hexdump -v -e '1/4 "%08x\n"' build/program.bin > build/program.hex

simulate file: clean (assemble file)
    mkdir -p build/sim
    ghdl -a --std=08 --workdir=build/sim ../shared/hdl/RiscVPkg.vhd
    ghdl -a --std=08 --workdir=build/sim ../shared/hdl/Ram.vhd
    ghdl -a --std=08 --workdir=build/sim ../shared/hdl/Registers.vhd
    ghdl -a --std=08 --workdir=build/sim ../shared/hdl/InstructionDecoder.vhd
    ghdl -a --std=08 --workdir=build/sim ../shared/hdl/Cpu.vhd
    ghdl -a --std=08 --workdir=build/sim ../shared/tb/CpuTb.vhd
    ghdl -r --std=08 --workdir=build/sim cputb --wave=build/sim/out.ghw

gui file: (simulate file)
    surfer -s cpu.surf.ron build/sim/out.ghw