-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package ClintRegisters_pkg is

    constant CLINTREGISTERS_DATA_WIDTH : positive := 32;
    constant CLINTREGISTERS_MIN_ADDR_WIDTH : positive := 16;
    constant CLINTREGISTERS_SIZE : positive := 49152;

    type \ClintRegisters.mtime.mtime_in_t\ is record
        next_q : std_logic_vector(31 downto 0);
    end record;

    type \ClintRegisters.mtime_in_t\ is record
        mtime : \ClintRegisters.mtime.mtime_in_t\;
    end record;

    type \ClintRegisters.mtimeh.mtimeh_in_t\ is record
        next_q : std_logic_vector(31 downto 0);
    end record;

    type \ClintRegisters.mtimeh_in_t\ is record
        mtimeh : \ClintRegisters.mtimeh.mtimeh_in_t\;
    end record;

    type ClintRegisters_in_t is record
        mtime : \ClintRegisters.mtime_in_t\;
        mtimeh : \ClintRegisters.mtimeh_in_t\;
    end record;

    type \ClintRegisters.msip.msip_out_t\ is record
        value : std_logic;
    end record;

    type \ClintRegisters.msip_out_t\ is record
        msip : \ClintRegisters.msip.msip_out_t\;
    end record;

    type \ClintRegisters.mtimecmp.mtimecmp_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \ClintRegisters.mtimecmp_out_t\ is record
        mtimecmp : \ClintRegisters.mtimecmp.mtimecmp_out_t\;
    end record;

    type \ClintRegisters.mtimecmph.mtimecmph_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \ClintRegisters.mtimecmph_out_t\ is record
        mtimecmph : \ClintRegisters.mtimecmph.mtimecmph_out_t\;
    end record;

    type ClintRegisters_out_t is record
        msip : \ClintRegisters.msip_out_t\;
        mtimecmp : \ClintRegisters.mtimecmp_out_t\;
        mtimecmph : \ClintRegisters.mtimecmph_out_t\;
    end record;
end package;
