MEMORY
{
    RAM_BOOT : ORIGIN = 0x01000000, LENGTH = 64K
    RAM_APP : ORIGIN = 0x02000000, LENGTH = 64K
}

REGION_ALIAS("REGION_TEXT", RAM_BOOT);
REGION_ALIAS("REGION_RODATA", RAM_BOOT);
REGION_ALIAS("REGION_DATA", RAM_BOOT);
REGION_ALIAS("REGION_BSS", RAM_BOOT);
REGION_ALIAS("REGION_HEAP", RAM_BOOT);
REGION_ALIAS("REGION_STACK", RAM_BOOT);