
build:
    PATH=/opt/xpack/xpack-riscv-none-elf-gcc-15.2.0-1/bin:$PATH \
        riscv-none-elf-gcc \
        -mabi=ilp32 -march=rv32i_zicsr -nostdlib \
        -nostartfiles -T linker.ld \
        -o ../build/coremark.elf \
        -I ../../submodules/coremark \
        -I . \
        start.S \
        core_portme.c ee_printf.c cvt.c \
        ../../submodules/coremark/core_main.c \
        ../../submodules/coremark/core_matrix.c \
        ../../submodules/coremark/core_state.c \
        ../../submodules/coremark/core_util.c \
        ../../submodules/coremark/core_list_join.c \
        -lc -lm -lgcc