-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package UartRegisters_pkg is

    constant UARTREGISTERS_DATA_WIDTH : positive := 32;
    constant UARTREGISTERS_MIN_ADDR_WIDTH : positive := 4;
    constant UARTREGISTERS_SIZE : positive := 16;

    type \UartRegisters.rx.rx_in_t\ is record
        next_q : std_logic_vector(7 downto 0);
    end record;

    type \UartRegisters.rx_in_t\ is record
        rx : \UartRegisters.rx.rx_in_t\;
    end record;

    type \UartRegisters.status.rxr_in_t\ is record
        next_q : std_logic;
    end record;

    type \UartRegisters.status.txe_in_t\ is record
        next_q : std_logic;
    end record;

    type \UartRegisters.status_in_t\ is record
        rxr : \UartRegisters.status.rxr_in_t\;
        txe : \UartRegisters.status.txe_in_t\;
    end record;

    type UartRegisters_in_t is record
        rx : \UartRegisters.rx_in_t\;
        status : \UartRegisters.status_in_t\;
    end record;

    type \UartRegisters.rx.rx_out_t\ is record
        swacc : std_logic;
    end record;

    type \UartRegisters.rx_out_t\ is record
        rx : \UartRegisters.rx.rx_out_t\;
    end record;

    type \UartRegisters.tx.tx_out_t\ is record
        value : std_logic_vector(7 downto 0);
        swacc : std_logic;
    end record;

    type \UartRegisters.tx_out_t\ is record
        tx : \UartRegisters.tx.tx_out_t\;
    end record;

    type \UartRegisters.ctrl.enable_out_t\ is record
        value : std_logic;
    end record;

    type \UartRegisters.ctrl_out_t\ is record
        enable : \UartRegisters.ctrl.enable_out_t\;
    end record;

    type \UartRegisters.status.rxr_out_t\ is record
        value : std_logic;
    end record;

    type \UartRegisters.status_out_t\ is record
        rxr : \UartRegisters.status.rxr_out_t\;
    end record;

    type UartRegisters_out_t is record
        rx : \UartRegisters.rx_out_t\;
        tx : \UartRegisters.tx_out_t\;
        ctrl : \UartRegisters.ctrl_out_t\;
        status : \UartRegisters.status_out_t\;
    end record;
end package;
