_default:
    @just --list

clean:
    rm -rf build sim_build
    cargo clean -r
    cargo clean -r --target riscv32i-unknown-none-elf

simulate elf: && gui
    mkdir -p build/sim
    riscv32-unknown-elf-objcopy -O binary {{elf}} build/program.bin
    hexdump -v -e '1/4 "%08x\n"' build/program.bin > build/program.hex
    uv run runner.py build/program.hex

gui:       
    surfer -s cpu.surf.ron build/sim/out.ghw

rust elf: && (simulate elf)
    mkdir -p build
    cp {{elf}} build/program.elf

decomp:
    cutter -A 1 build/program.elf