_default:
    @just --list

clean:
    rm -rf build sim_build

simulate: && gui
    mkdir -p build/sim
    riscv32-unknown-elf-objcopy -O binary build/program.elf build/program.bin
    hexdump -v -e '1/4 "%08x\n"' build/program.bin > build/program.hex
    uv run runner.py build/program.hex

gui:       
    surfer -s cpu.surf.ron build/sim/out.ghw

[no-cd]
rust path: && simulate
    mkdir -p ../build
    riscv32-unknown-elf-objdump -d -h {{path}} | head -n 100
    cp {{path}} ../build/program.elf