-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package CsrRegisters_pkg is

    constant CSRREGISTERS_DATA_WIDTH : positive := 32;
    constant CSRREGISTERS_MIN_ADDR_WIDTH : positive := 12;
    constant CSRREGISTERS_SIZE : positive := 3096;

    type \CsrRegisters.mstatus.sie_in_t\ is record
        next_q : std_logic;
    end record;

    type \CsrRegisters.mstatus.mie_in_t\ is record
        next_q : std_logic;
    end record;

    type \CsrRegisters.mstatus.spie_in_t\ is record
        next_q : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpie_in_t\ is record
        next_q : std_logic;
    end record;

    type \CsrRegisters.mstatus.spp_in_t\ is record
        next_q : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpp_in_t\ is record
        next_q : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus_in_t\ is record
        sie : \CsrRegisters.mstatus.sie_in_t\;
        mie : \CsrRegisters.mstatus.mie_in_t\;
        spie : \CsrRegisters.mstatus.spie_in_t\;
        mpie : \CsrRegisters.mstatus.mpie_in_t\;
        spp : \CsrRegisters.mstatus.spp_in_t\;
        mpp : \CsrRegisters.mstatus.mpp_in_t\;
    end record;

    type CsrRegisters_in_t is record
        mstatus : \CsrRegisters.mstatus_in_t\;
    end record;

    type \CsrRegisters.mstatus.sie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.spie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.ube_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.spp_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.vs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.mpp_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.fs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.xs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.mprv_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.sum_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mxr_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tvm_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tw_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tsr_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.spelp_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.sdt_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.sd_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus_out_t\ is record
        sie : \CsrRegisters.mstatus.sie_out_t\;
        mie : \CsrRegisters.mstatus.mie_out_t\;
        spie : \CsrRegisters.mstatus.spie_out_t\;
        ube : \CsrRegisters.mstatus.ube_out_t\;
        mpie : \CsrRegisters.mstatus.mpie_out_t\;
        spp : \CsrRegisters.mstatus.spp_out_t\;
        vs : \CsrRegisters.mstatus.vs_out_t\;
        mpp : \CsrRegisters.mstatus.mpp_out_t\;
        fs : \CsrRegisters.mstatus.fs_out_t\;
        xs : \CsrRegisters.mstatus.xs_out_t\;
        mprv : \CsrRegisters.mstatus.mprv_out_t\;
        sum : \CsrRegisters.mstatus.sum_out_t\;
        mxr : \CsrRegisters.mstatus.mxr_out_t\;
        tvm : \CsrRegisters.mstatus.tvm_out_t\;
        tw : \CsrRegisters.mstatus.tw_out_t\;
        tsr : \CsrRegisters.mstatus.tsr_out_t\;
        spelp : \CsrRegisters.mstatus.spelp_out_t\;
        sdt : \CsrRegisters.mstatus.sdt_out_t\;
        sd : \CsrRegisters.mstatus.sd_out_t\;
    end record;

    type \CsrRegisters.misa.misa_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.misa_out_t\ is record
        misa : \CsrRegisters.misa.misa_out_t\;
    end record;

    type \CsrRegisters.mie.mie_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mie_out_t\ is record
        mie : \CsrRegisters.mie.mie_out_t\;
    end record;

    type \CsrRegisters.mtvec.mtvec_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mtvec_out_t\ is record
        mtvec : \CsrRegisters.mtvec.mtvec_out_t\;
    end record;

    type CsrRegisters_out_t is record
        mstatus : \CsrRegisters.mstatus_out_t\;
        misa : \CsrRegisters.misa_out_t\;
        mie : \CsrRegisters.mie_out_t\;
        mtvec : \CsrRegisters.mtvec_out_t\;
    end record;
end package;
