-- Generated by PeakRDL-regblock-vhdl - A free and open-source VHDL generator
--  https://github.com/SystemRDL/PeakRDL-regblock-vhdl
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

package CsrRegisters_pkg is

    constant CSRREGISTERS_DATA_WIDTH : positive := 32;
    constant CSRREGISTERS_MIN_ADDR_WIDTH : positive := 14;
    constant CSRREGISTERS_SIZE : positive := 15448;

    type \CsrRegisters.mstatus.mie_in_t\ is record
        next_q : std_logic;
        we : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpie_in_t\ is record
        next_q : std_logic;
        we : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpp_in_t\ is record
        next_q : std_logic_vector(1 downto 0);
        we : std_logic;
    end record;

    type \CsrRegisters.mstatus_in_t\ is record
        mie : \CsrRegisters.mstatus.mie_in_t\;
        mpie : \CsrRegisters.mstatus.mpie_in_t\;
        mpp : \CsrRegisters.mstatus.mpp_in_t\;
    end record;

    type \CsrRegisters.mepc.mepc_in_t\ is record
        next_q : std_logic_vector(31 downto 0);
        we : std_logic;
    end record;

    type \CsrRegisters.mepc_in_t\ is record
        mepc : \CsrRegisters.mepc.mepc_in_t\;
    end record;

    type \CsrRegisters.mcause.code_in_t\ is record
        next_q : std_logic_vector(30 downto 0);
        we : std_logic;
    end record;

    type \CsrRegisters.mcause.interrupt_in_t\ is record
        next_q : std_logic;
        we : std_logic;
    end record;

    type \CsrRegisters.mcause_in_t\ is record
        code : \CsrRegisters.mcause.code_in_t\;
        interrupt : \CsrRegisters.mcause.interrupt_in_t\;
    end record;

    type \CsrRegisters.mtval.mtval_in_t\ is record
        next_q : std_logic_vector(31 downto 0);
        we : std_logic;
    end record;

    type \CsrRegisters.mtval_in_t\ is record
        mtval : \CsrRegisters.mtval.mtval_in_t\;
    end record;

    type \CsrRegisters.mip.meip_in_t\ is record
        next_q : std_logic;
        we : std_logic;
    end record;

    type \CsrRegisters.mip_in_t\ is record
        meip : \CsrRegisters.mip.meip_in_t\;
    end record;

    type CsrRegisters_in_t is record
        mstatus : \CsrRegisters.mstatus_in_t\;
        mepc : \CsrRegisters.mepc_in_t\;
        mcause : \CsrRegisters.mcause_in_t\;
        mtval : \CsrRegisters.mtval_in_t\;
        mip : \CsrRegisters.mip_in_t\;
    end record;

    type \CsrRegisters.mstatus.sie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.spie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.ube_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mpie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.spp_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.vs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.mpp_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.fs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.xs_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mstatus.mprv_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.sum_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.mxr_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tvm_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tw_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.tsr_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus.sd_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatus_out_t\ is record
        sie : \CsrRegisters.mstatus.sie_out_t\;
        mie : \CsrRegisters.mstatus.mie_out_t\;
        spie : \CsrRegisters.mstatus.spie_out_t\;
        ube : \CsrRegisters.mstatus.ube_out_t\;
        mpie : \CsrRegisters.mstatus.mpie_out_t\;
        spp : \CsrRegisters.mstatus.spp_out_t\;
        vs : \CsrRegisters.mstatus.vs_out_t\;
        mpp : \CsrRegisters.mstatus.mpp_out_t\;
        fs : \CsrRegisters.mstatus.fs_out_t\;
        xs : \CsrRegisters.mstatus.xs_out_t\;
        mprv : \CsrRegisters.mstatus.mprv_out_t\;
        sum : \CsrRegisters.mstatus.sum_out_t\;
        mxr : \CsrRegisters.mstatus.mxr_out_t\;
        tvm : \CsrRegisters.mstatus.tvm_out_t\;
        tw : \CsrRegisters.mstatus.tw_out_t\;
        tsr : \CsrRegisters.mstatus.tsr_out_t\;
        sd : \CsrRegisters.mstatus.sd_out_t\;
    end record;

    type \CsrRegisters.misa.a_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.b_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.c_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.d_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.e_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.f_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.h_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.i_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.m_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.n_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.p_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.q_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.s_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.u_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.v_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.x_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.misa.mxl_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.misa_out_t\ is record
        a : \CsrRegisters.misa.a_out_t\;
        b : \CsrRegisters.misa.b_out_t\;
        c : \CsrRegisters.misa.c_out_t\;
        d : \CsrRegisters.misa.d_out_t\;
        e : \CsrRegisters.misa.e_out_t\;
        f : \CsrRegisters.misa.f_out_t\;
        h : \CsrRegisters.misa.h_out_t\;
        i : \CsrRegisters.misa.i_out_t\;
        m : \CsrRegisters.misa.m_out_t\;
        n : \CsrRegisters.misa.n_out_t\;
        p : \CsrRegisters.misa.p_out_t\;
        q : \CsrRegisters.misa.q_out_t\;
        s : \CsrRegisters.misa.s_out_t\;
        u : \CsrRegisters.misa.u_out_t\;
        v : \CsrRegisters.misa.v_out_t\;
        x : \CsrRegisters.misa.x_out_t\;
        mxl : \CsrRegisters.misa.mxl_out_t\;
    end record;

    type \CsrRegisters.medeleg.medeleg_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.medeleg_out_t\ is record
        medeleg : \CsrRegisters.medeleg.medeleg_out_t\;
    end record;

    type \CsrRegisters.mideleg.mideleg_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mideleg_out_t\ is record
        mideleg : \CsrRegisters.mideleg.mideleg_out_t\;
    end record;

    type \CsrRegisters.mie.ssie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie.msie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie.stie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie.mtie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie.seie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie.meie_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mie_out_t\ is record
        ssie : \CsrRegisters.mie.ssie_out_t\;
        msie : \CsrRegisters.mie.msie_out_t\;
        stie : \CsrRegisters.mie.stie_out_t\;
        mtie : \CsrRegisters.mie.mtie_out_t\;
        seie : \CsrRegisters.mie.seie_out_t\;
        meie : \CsrRegisters.mie.meie_out_t\;
    end record;

    type \CsrRegisters.mtvec.mode_out_t\ is record
        value : std_logic_vector(1 downto 0);
    end record;

    type \CsrRegisters.mtvec.base_out_t\ is record
        value : std_logic_vector(29 downto 0);
    end record;

    type \CsrRegisters.mtvec_out_t\ is record
        mode : \CsrRegisters.mtvec.mode_out_t\;
        base : \CsrRegisters.mtvec.base_out_t\;
    end record;

    type \CsrRegisters.mstatush.sbe_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush.mbe_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush.gva_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush.mpv_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush.mpelp_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush.mdt_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mstatush_out_t\ is record
        sbe : \CsrRegisters.mstatush.sbe_out_t\;
        mbe : \CsrRegisters.mstatush.mbe_out_t\;
        gva : \CsrRegisters.mstatush.gva_out_t\;
        mpv : \CsrRegisters.mstatush.mpv_out_t\;
        mpelp : \CsrRegisters.mstatush.mpelp_out_t\;
        mdt : \CsrRegisters.mstatush.mdt_out_t\;
    end record;

    type \CsrRegisters.medelegh.medelegh_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.medelegh_out_t\ is record
        medelegh : \CsrRegisters.medelegh.medelegh_out_t\;
    end record;

    type \CsrRegisters.mepc.mepc_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mepc_out_t\ is record
        mepc : \CsrRegisters.mepc.mepc_out_t\;
    end record;

    type \CsrRegisters.mcause.code_out_t\ is record
        value : std_logic_vector(30 downto 0);
    end record;

    type \CsrRegisters.mcause.interrupt_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mcause_out_t\ is record
        code : \CsrRegisters.mcause.code_out_t\;
        interrupt : \CsrRegisters.mcause.interrupt_out_t\;
    end record;

    type \CsrRegisters.mtval.mtval_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mtval_out_t\ is record
        mtval : \CsrRegisters.mtval.mtval_out_t\;
    end record;

    type \CsrRegisters.mip.ssip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip.msip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip.stip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip.mtip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip.seip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip.meip_out_t\ is record
        value : std_logic;
    end record;

    type \CsrRegisters.mip_out_t\ is record
        ssip : \CsrRegisters.mip.ssip_out_t\;
        msip : \CsrRegisters.mip.msip_out_t\;
        stip : \CsrRegisters.mip.stip_out_t\;
        mtip : \CsrRegisters.mip.mtip_out_t\;
        seip : \CsrRegisters.mip.seip_out_t\;
        meip : \CsrRegisters.mip.meip_out_t\;
    end record;

    type \CsrRegisters.mvendorid.offset_out_t\ is record
        value : std_logic_vector(6 downto 0);
    end record;

    type \CsrRegisters.mvendorid.bank_out_t\ is record
        value : std_logic_vector(24 downto 0);
    end record;

    type \CsrRegisters.mvendorid_out_t\ is record
        offset : \CsrRegisters.mvendorid.offset_out_t\;
        bank : \CsrRegisters.mvendorid.bank_out_t\;
    end record;

    type \CsrRegisters.marchid.marchid_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.marchid_out_t\ is record
        marchid : \CsrRegisters.marchid.marchid_out_t\;
    end record;

    type \CsrRegisters.mimpid.mimpid_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mimpid_out_t\ is record
        mimpid : \CsrRegisters.mimpid.mimpid_out_t\;
    end record;

    type \CsrRegisters.mhartid.mhartid_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mhartid_out_t\ is record
        mhartid : \CsrRegisters.mhartid.mhartid_out_t\;
    end record;

    type \CsrRegisters.mconfigptr.mconfigptr_out_t\ is record
        value : std_logic_vector(31 downto 0);
    end record;

    type \CsrRegisters.mconfigptr_out_t\ is record
        mconfigptr : \CsrRegisters.mconfigptr.mconfigptr_out_t\;
    end record;

    type CsrRegisters_out_t is record
        mstatus : \CsrRegisters.mstatus_out_t\;
        misa : \CsrRegisters.misa_out_t\;
        medeleg : \CsrRegisters.medeleg_out_t\;
        mideleg : \CsrRegisters.mideleg_out_t\;
        mie : \CsrRegisters.mie_out_t\;
        mtvec : \CsrRegisters.mtvec_out_t\;
        mstatush : \CsrRegisters.mstatush_out_t\;
        medelegh : \CsrRegisters.medelegh_out_t\;
        mepc : \CsrRegisters.mepc_out_t\;
        mcause : \CsrRegisters.mcause_out_t\;
        mtval : \CsrRegisters.mtval_out_t\;
        mip : \CsrRegisters.mip_out_t\;
        mvendorid : \CsrRegisters.mvendorid_out_t\;
        marchid : \CsrRegisters.marchid_out_t\;
        mimpid : \CsrRegisters.mimpid_out_t\;
        mhartid : \CsrRegisters.mhartid_out_t\;
        mconfigptr : \CsrRegisters.mconfigptr_out_t\;
    end record;
end package;
